const columnLabels = {
  matchid: "Match ID",
  blueteamfirstblood: "Blue Team First Blood",
  blueteamtotalkills: "Blue Team Total Kills",
  blueteamdragonkills: "Blue Team Dragon Kills",
  blueteamheraldkills: "Blue Team Herald Kills",
  blueteamtowersdestroyed: "Blue Team Towers Destroyed",
  blueteaminhibitorsdestroyed: "Blue Team Inhibitors Destroyed",
  blueteamturretplatesdestroyed: "Blue Team Turret Plates Destroyed",
  blueteamjungleminions: "Blue Team Jungle Minions",
  blueteamminionskilled: "Blue Team Minions Killed",
  blueteamxp: "Blue Team XP",
  blueteamtotalgold: "Blue Team Gold",
  blueteamtotaldamagetochamps: "Blue Team Damage to Champions",
  blueteamwardsplaced: "Blue Team Wards Placed",
  blueteamcontrolwardsplaced: "Blue Team Control Wards",
  redteamtotalkills: "Red Team Total Kills",
  redteamdragonkills: "Red Team Dragon Kills",
  redteamheraldkills: "Red Team Herald Kills",
  redteamtowersdestroyed: "Red Team Towers Destroyed",
  redteaminhibitorsdestroyed: "Red Team Inhibitors Destroyed",
  redteamturretplatesdestroyed: "Red Team Turret Plates Destroyed",
  redteamjungleminions: "Red Team Jungle Minions",
  redteamminionskilled: "Red Team Minions Killed",
  redteamxp: "Red Team XP",
  redteamtotalgold: "Red Team Gold",
  redteamtotaldamagetochamps: "Red Team Damage to Champions",
  redteamwardsplaced: "Red Team Wards Placed",
  redteamcontrolwardsplaced: "Red Team Control Wards",
  bluewin: "Blue Win",
  gold_difference: "Gold Difference",
};

export default columnLabels;